import React from 'react';
import Accordion from '@/components/accordion';
import SearchableProductDropdown from '@/components/products/SearchableProductDropdown';
import Input from '@/components/customInput';

interface ProductSectionProps {
  accordionData: any;
  categories: any[];
  brandOptions: any[];
  expandedAccordionIndex: number;
  onAccordionClick: (index: number) => void;
  accordionMethods: any;
  products: any[]; // Changed from stock to products
}

const ProductSection: React.FC<ProductSectionProps> = ({
  accordionData,
  categories,
  brandOptions,
  expandedAccordionIndex,
  onAccordionClick,
  accordionMethods,
  products,
}) => {
  const getAccordionContent = (accordionIndex: number) => {
    const accordionDataItem = accordionData[accordionIndex];
    
    if (!accordionDataItem) {
      return null;
    }

    // Get all available products from products data (same as products page)
    const getAllProducts = () => {
      const productOptions: any[] = [];

      if (!products || !Array.isArray(products) || products.length === 0) {
        return productOptions;
      }

      products.forEach((product: any, index: number) => {
        // Check if product is active and has stock
        const stockQuantity = product.stock || 0;
        const isActive = product.isActive !== false; // Default to true if not specified

        if (isActive && stockQuantity > 0) {
          // Find category name for display - include full hierarchy
          let categoryName = 'No Category';
          let fullCategoryPath = 'No Category';

          if (product.productCategories && product.productCategories.length > 0) {
            const categoryItem = product.productCategories[0];

            if (typeof categoryItem === 'string') {
              // Direct category ID string
              const category = categories.find(cat => cat._id === categoryItem || cat.id === categoryItem);
              if (category) {
                categoryName = category.name || category.brandName;
                fullCategoryPath = category.brandName;
              }
            } else if (typeof categoryItem === 'object' && categoryItem) {
              // Category object - build full hierarchy
              const categoryParts: string[] = [];

              // Add parent category first
              if (categoryItem.parentCategory) {
                const parentCategory = categories.find(cat =>
                  cat._id === categoryItem.parentCategory || cat.id === categoryItem.parentCategory
                );

                if (parentCategory && parentCategory.name) {
                  categoryParts.push(parentCategory.name);
                }
              }

              // Add subcategory
              if (categoryItem.name) {
                categoryParts.push(categoryItem.name);
              }

              categoryName = categoryItem.name || 'Unknown';
              fullCategoryPath = categoryParts.length > 0 ? categoryParts.join(' → ') : categoryName;
            }
          }

          const productOption = {
            label: `${product.name} (${fullCategoryPath})`,
            value: product._id || product.id,
            productId: product._id || product.id,
            productName: product.name,
            category: categoryName,
            fullCategoryPath: fullCategoryPath,
            productCategories: product.productCategories,
            price: product.price || 0,
            cost: product.cost || 0,
            stockQuantity: stockQuantity,
            sku: product.sku || '',
            unit: product.unit || 'pcs',
            specifications: product.specifications || {},
          };

          productOptions.push(productOption);
        } else {
        }
      });

      return productOptions;
    };

    const selectedCategory = accordionDataItem.category || '';
    const isBatteryCategory = selectedCategory === 'Batteries';

    return (
      <div className='w-full'>
        <div className='w-full my-4'>
          {(() => {
            let selectedProduct = products.find(p => (p._id || p.id) === accordionDataItem.productId);
            
            // Fallback: try to find by name if ID matching fails
            if (!selectedProduct && accordionDataItem.productName) {
              selectedProduct = products.find(p => p.name === accordionDataItem.productName);
            }
            
            const currentValue = selectedProduct ? {
              id: selectedProduct._id || selectedProduct.id || '',
              name: selectedProduct.name,
              category: selectedProduct.category,
              breadcrumb: [] // Will be generated by component
            } : null;

            return (
              <SearchableProductDropdown
                products={products}
                value={currentValue}
                onChange={(selectedProduct: any) => {
                  if (!selectedProduct) return;

                  const product = products.find(p => (p._id || p.id) === selectedProduct.id);
                  if (!product) return;

                  // Set product details in accordion data
                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'productId',
                    selectedProduct.id
                  );
                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'productName',
                    selectedProduct.name
                  );
                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'productPrice',
                    product.price || 0
                  );
                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'productCategories',
                    product.productCategories || []
                  );

                  console.log('🔍 Product selected - setting accordion data:', {
                    productId: selectedProduct.id,
                    productName: selectedProduct.name,
                    productCategories: product.productCategories,
                    breadcrumb: selectedProduct.breadcrumb
                  });

                  // Check if product belongs to Batteries category by checking breadcrumb
                  let isBatteryProduct = false;

                  if (selectedProduct.breadcrumb && selectedProduct.breadcrumb.length > 0) {
                    // Check if any category in breadcrumb is "Batteries"
                    isBatteryProduct = selectedProduct.breadcrumb.some((item: any) =>
                      item.name.toLowerCase().includes('batter')
                    );
                  }

                  // Fallback checks
                  if (!isBatteryProduct && product.category) {
                    const categoryName = product.category.brandName || product.category.name || '';
                    isBatteryProduct = categoryName.toLowerCase().includes('batter');
                  }

                  if (!isBatteryProduct && product.specifications && (product.specifications.plateCount || product.specifications.ah)) {
                    isBatteryProduct = true;
                  }

                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'isBattery',
                    isBatteryProduct
                  );

                  if (isBatteryProduct && product.specifications) {
                    accordionMethods.handleAccordionChange(
                      accordionIndex,
                      'batteryDetails',
                      product.specifications
                    );
                  }
                }}
                placeholder="Select Product"
              />
            );
          })()}
        </div>

        {/* Product Details - Show when product is selected */}
        {accordionDataItem.productId && (() => {
          const selectedProduct = products.find(p => (p._id || p.id) === accordionDataItem.productId);
          if (!selectedProduct) return null;

          // Get all category names in hierarchy
          const getCategoryHierarchy = () => {
            // First try to use the breadcrumb from category
            if (selectedProduct.category?.breadcrumb && Array.isArray(selectedProduct.category.breadcrumb)) {
              return selectedProduct.category.breadcrumb.map((item: any) => item.name);
            }
            
            // Fallback to productCategories if available
            if (!selectedProduct.productCategories || selectedProduct.productCategories.length === 0) {
              return [accordionDataItem.category || 'N/A'];
            }

            const categoryNames: string[] = [];

            selectedProduct.productCategories.forEach((categoryItem: any) => {
              if (typeof categoryItem === 'string') {
                // Direct category ID string
                const category = categories.find(cat =>
                  cat._id === categoryItem || cat.id === categoryItem
                );
                if (category && category.name) {
                  categoryNames.push(category.name);
                }
              } else if (typeof categoryItem === 'object' && categoryItem) {
                // Category object - add parent category first if exists
                if (categoryItem.parentCategory) {
                  const parentCategory = categories.find(cat =>
                    cat._id === categoryItem.parentCategory || cat.id === categoryItem.parentCategory
                  );
                  if (parentCategory && parentCategory.name) {
                    categoryNames.push(parentCategory.name);
                  }
                }
                // Then add the subcategory name
                if (categoryItem.name) {
                  categoryNames.push(categoryItem.name);
                }
              }
            });

            return categoryNames.length > 0 ? categoryNames : [accordionDataItem.category || 'N/A'];
          };

          const categoryHierarchy = getCategoryHierarchy();

          return (
            <div className='mb-4 rounded-lg border border-gray-200 bg-gray-50 p-3'>
              <div className='flex gap-4 text-sm'>
                <div>
                  <span className='text-gray-600'>Name:</span>
                  <span className='ml-2 text-gray-900'>{selectedProduct.name}</span>
                </div>
                <div>
                  <span className='text-gray-600'>Categories:</span>
                  <span className='ml-2 text-gray-900'>{categoryHierarchy.join(' → ')}</span>
                </div>
              </div>
            </div>
          );
        })()}

        <div className='mb-4 grid w-full grid-cols-2 gap-4'>
          <div className='w-full'>
            <Input
              parentClass='w-full'
              type='number'
              label='Product Price'
              name='productPrice'
              min={1}
              step='0.01'
              required
              value={accordionDataItem.productPrice}
              onChange={(e) => {
                accordionMethods.handleAccordionChange(
                  accordionIndex,
                  'productPrice',
                  e.target.value
                );
              }}
            />
          </div>
          <div className='w-full'>
            <Input
              parentClass='w-full'
              type='number'
              label='Quantity'
              value={accordionDataItem.quantity}
              onChange={(e) => {
                accordionMethods.handleAccordionChange(
                  accordionIndex,
                  'quantity',
                  e.target.value
                );
              }}
            />
          </div>
        </div>

        {/* Warranty Fields - Show when category hierarchy includes battery */}
        {(() => {
          const selectedProduct = products.find(p => (p._id || p.id) === accordionDataItem.productId);
          if (!selectedProduct) return false;

          // Use same logic as categoryHierarchy in product preview
          const categoryNames: string[] = [];
          selectedProduct.productCategories?.forEach((categoryItem: any) => {
            if (typeof categoryItem === 'string') {
              const category = categories.find(cat =>
                cat._id === categoryItem || cat.id === categoryItem
              );
              if (category && category.name) {
                categoryNames.push(category.name);
              }
            } else if (typeof categoryItem === 'object' && categoryItem) {
              if (categoryItem.parentCategory) {
                const parentCategory = categories.find(cat =>
                  cat._id === categoryItem.parentCategory || cat.id === categoryItem.parentCategory
                );
                if (parentCategory && parentCategory.name) {
                  categoryNames.push(parentCategory.name);
                }
              }
              if (categoryItem.name) {
                categoryNames.push(categoryItem.name);
              }
            }
          });

          const categoryHierarchy = categoryNames.join(' → ');
          return categoryHierarchy.toLowerCase().includes('batter');
        })() && (
          <div className='mb-4'>
            <div className='mb-2'>
              <label className='text-sm font-medium text-gray-700'>Warranty</label>
            </div>
            <div className='grid w-full grid-cols-2 gap-4'>
              <div className='w-full'>
                <label className='flex items-center'>
                  <input
                    type='checkbox'
                    checked={accordionDataItem.noWarranty || false}
                    onChange={(e) => {
                      accordionMethods.handleAccordionChange(
                        accordionIndex,
                        'noWarranty',
                        e.target.checked
                      );
                    }}
                    className='mr-2'
                  />
                  No Warranty
                </label>
              </div>
              {!accordionDataItem.noWarranty && (
                <>
                  <div className='w-full'>
                    <Input
                      parentClass='w-full'
                      type='date'
                      label='Warranty Start Date'
                      name='warrentyStartDate'
                      value={accordionDataItem.warrentyStartDate || ''}
                      onChange={(e) => {
                        accordionMethods.handleAccordionChange(
                          accordionIndex,
                          'warrentyStartDate',
                          e.target.value
                        );
                      }}
                    />
                  </div>
                  <div className='w-full'>
                    <Input
                      parentClass='w-full'
                      type='number'
                      label='Warranty Duration (Months)'
                      name='warrentyDuration'
                      min={1}
                      value={accordionDataItem.warrentyDuration || ''}
                      onChange={(e) => {
                        accordionMethods.handleAccordionChange(
                          accordionIndex,
                          'warrentyDuration',
                          e.target.value
                        );
                      }}
                    />
                  </div>
                  <div className='w-full'>
                    <Input
                      parentClass='w-full'
                      type='text'
                      label='Warranty Code'
                      name='warrentyCode'
                      value={accordionDataItem.warrentyCode || ''}
                      onChange={(e) => {
                        accordionMethods.handleAccordionChange(
                          accordionIndex,
                          'warrentyCode',
                          e.target.value
                        );
                      }}
                    />
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        {/* Check if current series is battery tonic */}
        {(() => {
          const selectedProduct = products.find(p => (p._id || p.id) === accordionDataItem.productId);
          const currentSeries = accordionDataItem.series || '';
          const isBatteryTonic =
            currentSeries &&
            (currentSeries.toLowerCase().includes('tonic') ||
              currentSeries.toLowerCase().includes('ml') ||
              (currentSeries.toLowerCase().includes('battery') &&
                currentSeries.toLowerCase().includes('water')) ||
              currentSeries.toLowerCase().includes('distilled'));

          // Check if selected product is a battery
          const isBatteryProduct = accordionDataItem.isBattery || 
            (selectedProduct?.productCategories && 
              selectedProduct.productCategories.some((cat: any) => {
                if (typeof cat === 'string') {
                  const category = categories.find(c => c._id === cat || c.id === cat);
                  return category?.name?.toLowerCase().includes('batter');
                } else if (cat?.name) {
                  return cat.name.toLowerCase().includes('batter');
                }
                return false;
              })) ||
            (accordionDataItem.batteryDetails && (accordionDataItem.batteryDetails.plateCount || accordionDataItem.batteryDetails.ah));

          // Only show warranty toggle for battery products (but not battery tonic)
          if (!isBatteryProduct || isBatteryTonic) {
            return null;
          }

          // If it's battery tonic, show info message instead of toggle
          if (isBatteryTonic) {
            return (
              <div className='mb-4 rounded-lg border border-blue-200 bg-blue-50 p-4'>
                <div className='flex items-center'>
                  <div className='flex-shrink-0'>
                    <svg
                      className='h-5 w-5 text-blue-400'
                      viewBox='0 0 20 20'
                      fill='currentColor'
                    >
                      <path
                        fillRule='evenodd'
                        d='M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z'
                        clipRule='evenodd'
                      />
                    </svg>
                  </div>
                  <div className='ml-3 flex-1'>
                    <p className='text-sm font-medium text-blue-800'>
                      Battery Tonic (Distilled Water) - No Warranty Required
                    </p>
                    <p className='mt-1 text-xs text-blue-700'>
                      Warranty fields are not applicable for this product type.
                    </p>
                  </div>
                </div>
              </div>
            );
          }

          // For regular batteries, show the warranty toggle
          return (
            <div className='mb-4 rounded-lg border border-gray-200 bg-gray-50 p-4'>
              <div className='flex items-center justify-between'>
                <div className='flex flex-col'>
                  <label className='text-sm font-semibold text-gray-800'>
                    No Warranty
                  </label>
                  <p className='mt-1 text-xs text-gray-600'>
                    {accordionDataItem.noWarranty
                      ? 'This product has no warranty coverage'
                      : 'Enable if this product has no warranty'}
                  </p>
                </div>
                <div className='flex items-center space-x-3'>
                  <button
                    type='button'
                    className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors focus:outline-none focus:ring-4 focus:ring-red-200 ${
                      accordionDataItem.noWarranty
                        ? 'bg-red-500'
                        : 'bg-gray-300'
                    }`}
                    onClick={() => {
                      const newValue = !accordionDataItem.noWarranty;
                      accordionMethods.handleAccordionChange(
                        accordionIndex,
                        'noWarranty',
                        newValue
                      );
                    }}
                  >
                    <span
                      className={`inline-block h-6 w-6 transform rounded-full bg-white transition-transform ${
                        accordionDataItem.noWarranty
                          ? 'translate-x-6'
                          : 'translate-x-0.5'
                      }`}
                    />
                  </button>
                  <span
                    className={`text-sm font-medium ${accordionDataItem.noWarranty ? 'text-red-600' : 'text-gray-600'}`}
                  >
                    {accordionDataItem.noWarranty
                      ? 'No Warranty'
                      : 'Has Warranty'}
                  </span>
                </div>
              </div>
            </div>
          );
        })()}

        {/* Only show warranty fields if warranty is enabled and NOT battery tonic AND product is a battery */}
        {(() => {
          const selectedProduct = products.find(p => (p._id || p.id) === accordionDataItem.productId);
          const currentSeries = accordionDataItem.series || '';
          const isBatteryTonic =
            currentSeries &&
            (currentSeries.toLowerCase().includes('tonic') ||
              currentSeries.toLowerCase().includes('ml') ||
              (currentSeries.toLowerCase().includes('battery') &&
                currentSeries.toLowerCase().includes('water')) ||
              currentSeries.toLowerCase().includes('distilled'));
          
          // Check if selected product is a battery
          const isBatteryProduct = accordionDataItem.isBattery || 
            (selectedProduct?.productCategories && 
              selectedProduct.productCategories.some((cat: any) => {
                if (typeof cat === 'string') {
                  const category = categories.find(c => c._id === cat || c.id === cat);
                  return category?.name?.toLowerCase().includes('batter');
                } else if (cat?.name) {
                  return cat.name.toLowerCase().includes('batter');
                }
                return false;
              })) ||
            (accordionDataItem.batteryDetails && (accordionDataItem.batteryDetails.plateCount || accordionDataItem.batteryDetails.ah));
          
          // Don't show warranty fields if it's battery tonic OR if noWarranty is true OR if product is not a battery
          return !accordionDataItem.noWarranty && !isBatteryTonic && isBatteryProduct;
        })() && (
          <>
            <div className='mb-4 grid w-full grid-cols-2 gap-4'>
              <div className='w-full'>
                <Input
                  parentClass='w-full'
                  type='date'
                  label='Warranty Start Date'
                  name='warrentyStartDate'
                  value={accordionDataItem.warrentyStartDate}
                  onChange={(e) =>
                    accordionMethods.handleAccordionChange(
                      accordionIndex,
                      'warrentyStartDate',
                      e.target.value
                    )
                  }
                />
              </div>
              <div className='w-full'>
                <Input
                  parentClass='w-full'
                  type='number'
                  label='Warranty Duration (Months)'
                  name='warrentyDuration'
                  min={0}
                  max={120}
                  placeholder='0-120 months (0 for no warranty)'
                  value={accordionDataItem.warrentyDuration || ''}
                  onChange={(e) => {
                    const value = e.target.value;
                    // Ensure value is not negative and not greater than 120, allow 0 for no warranty
                    const numValue = parseInt(value);
                    if (value === '' || (numValue >= 0 && numValue <= 120)) {
                      accordionMethods.handleAccordionChange(
                        accordionIndex,
                        'warrentyDuration',
                        value
                      );
                    }
                  }}
                />
              </div>
            </div>

            <div className='mb-4 w-full'>
              <Input
                parentClass='w-full'
                type='text'
                label='Warranty Code'
                name='warrentyCode'
                placeholder='Enter warranty code(s) - multiple codes separated by comma or space'
                value={accordionDataItem.warrentyCode}
                onChange={(e) =>
                  accordionMethods.handleAccordionChange(
                    accordionIndex,
                    'warrentyCode',
                    e.target.value
                  )
                }
              />
            </div>
          </>
        )}
      </div>
    );
  };

  return (
    <>
      {Object.keys(accordionData).map((accordionIndex: any, index) => (
        <Accordion
          addOnClick={() =>
            accordionMethods.handleAddAccordion(Number(accordionIndex))
          }
          index={index}
          addIconClass={`${index === Object.keys(accordionData).length - 1 ? '' : 'hidden'}`}
          removeIconClass={`${index === 0 ? 'hidden' : ''}`}
          removeOnClick={() => {
            accordionMethods.handleRemoveAccordion(
              parseInt(accordionIndex, 10)
            );
          }}
          expandedAccordionIndex={expandedAccordionIndex}
          handleAccordionClick={onAccordionClick}
          key={accordionIndex}
          title={`Row ${accordionIndex}`}
          content={getAccordionContent(parseInt(accordionIndex, 10))}
        />
      ))}
    </>
  );
};

export default ProductSection;
